version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-bot
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - ./database:/app/database
    env_file:
      - .env
    command: >
      sh -c "bun install &&
             mkdir -p /app/database &&
             bun run index.ts"

volumes:
  database:
