version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite-data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_ROLE_ID=${DISCORD_ROLE_ID}
      - PORT=${PORT}
      - TEST_DISCORD_ID=${TEST_DISCORD_ID}

volumes:
  sqlite-data:
