version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Exclude node_modules from being overwritten
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_ROLE_ID=${DISCORD_ROLE_ID}
      - PORT=${PORT}
      - TEST_DISCORD_ID=${TEST_DISCORD_ID}
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/data
    command: ["sqlite3", "/data/roleData.db", ".databases"] # Correct SQLite initialization
    restart: always

volumes:
  sqlite-data:
